// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NFDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NFMsg {

  /// <summary>Holder for reflection information generated from NFDefine.proto</summary>
  public static partial class NFDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for NFDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NFDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ORkRlZmluZS5wcm90bxIFTkZNc2cqggQKDkVHYW1lRXZlbnRDb2RlEgsK",
            "B1NVQ0NFU1MQABIQCgxVTktPV05fRVJST1IQARIRCg1BQ0NPVU5UX0VYSVNU",
            "EAISFgoSQUNDT1VOVFBXRF9JTlZBTElEEAMSEQoNQUNDT1VOVF9VU0lORxAE",
            "EhIKDkFDQ09VTlRfTE9DS0VEEAUSGQoVQUNDT1VOVF9MT0dJTl9TVUNDRVNT",
            "EAYSFgoSVkVSSUZZX0tFWV9TVUNDRVNTEAcSEwoPVkVSSUZZX0tFWV9GQUlM",
            "EAgSGAoUU0VMRUNUU0VSVkVSX1NVQ0NFU1MQCRIVChFTRUxFQ1RTRVJWRVJf",
            "RkFJTBAKEhMKD0NIQVJBQ1RFUl9FWElTVBBuEhUKEVNWUlpPTkVJRF9JTlZB",
            "TElEEG8SFAoQQ0hBUkFDVEVSX05VTU9VVBBwEhUKEUNIQVJBQ1RFUl9JTlZB",
            "TElEEHESFgoSQ0hBUkFDVEVSX05PVEVYSVNUEHISEwoPQ0hBUkFDVEVSX1VT",
            "SU5HEHMSFAoQQ0hBUkFDVEVSX0xPQ0tFRBB0EhEKDVpPTkVfT1ZFUkxPQUQQ",
            "dRIOCgpOT1RfT05MSU5FEHYSGQoUSU5TVUZGSUNJRU5UX0RJQU1PTkQQyAES",
            "FgoRSU5TVUZGSUNJRU5UX0dPTEQQyQESFAoPSU5TVUZGSUNJRU5UX1NQEMoB",
            "KukPCgpFR2FtZU1zZ0lEEgoKBlVOS05PVxAAEhAKDEVWRU5UX1JFU1VMVBAB",
            "EhMKD0VWRU5UX1RSQU5TUE9SVBACEhAKDENMT1NFX1NPQ0tFVBADEhgKFFdU",
            "TV9XT1JMRF9SRUdJU1RFUkVEEAoSGgoWV1RNX1dPUkxEX1VOUkVHSVNURVJF",
            "RBALEhUKEVdUTV9XT1JMRF9SRUZSRVNIEAwSGAoUTFRNX0xPR0lOX1JFR0lT",
            "VEVSRUQQFBIaChZMVE1fTE9HSU5fVU5SRUdJU1RFUkVEEBUSFQoRTFRNX0xP",
            "R0lOX1JFRlJFU0gQFhIZChVQVFdHX1BST1hZX1JFR0lTVEVSRUQQHhIbChdQ",
            "VFdHX1BST1hZX1VOUkVHSVNURVJFRBAfEhYKElBUV0dfUFJPWFlfUkVGUkVT",
            "SBAgEhcKE0dUV19HQU1FX1JFR0lTVEVSRUQQKBIZChVHVFdfR0FNRV9VTlJF",
            "R0lTVEVSRUQQKRIUChBHVFdfR0FNRV9SRUZSRVNIECoSFQoRRFRXX0RCX1JF",
            "R0lTVEVSRUQQPBIXChNEVFdfREJfVU5SRUdJU1RFUkVEED0SEgoORFRXX0RC",
            "X1JFRlJFU0gQPhIQCgxTVFNfTkVUX0lORk8QRhIQCgxSRVFfTEFHX1RFU1QQ",
            "UBIVChFBQ0tfR0FURV9MQUdfVEVTVBBREhUKEUFDS19HQU1FX0xBR19URVNU",
            "EFISFQoRU1RTX1NFUlZFUl9SRVBPUlQQWhISCg5TVFNfSEVBUlRfQkVBVBBk",
            "Eg0KCVJFUV9MT0dJThBlEg0KCUFDS19MT0dJThBmEg4KClJFUV9MT0dPVVQQ",
            "ZxISCg5SRVFfV09STERfTElTVBBuEhIKDkFDS19XT1JMRF9MSVNUEG8SFQoR",
            "UkVRX0NPTk5FQ1RfV09STEQQcBIVChFBQ0tfQ09OTkVDVF9XT1JMRBBxEhkK",
            "FVJFUV9LSUNLRURfRlJPTV9XT1JMRBByEhMKD1JFUV9DT05ORUNUX0tFWRB4",
            "EhMKD0FDS19DT05ORUNUX0tFWRB6EhYKEVJFUV9TRUxFQ1RfU0VSVkVSEIIB",
            "EhYKEUFDS19TRUxFQ1RfU0VSVkVSEIMBEhIKDVJFUV9ST0xFX0xJU1QQhAES",
            "EgoNQUNLX1JPTEVfTElTVBCFARIUCg9SRVFfQ1JFQVRFX1JPTEUQhgESFAoP",
            "UkVRX0RFTEVURV9ST0xFEIcBEhUKEFJFUV9SRUNPVkVSX1JPTEUQiAESFwoS",
            "UkVRX0xPQURfUk9MRV9EQVRBEIwBEhcKEkFDS19MT0FEX1JPTEVfREFUQRCN",
            "ARIXChJSRVFfU0FWRV9ST0xFX0RBVEEQjgESFwoSQUNLX1NBVkVfUk9MRV9E",
            "QVRBEI8BEhMKDlJFUV9FTlRFUl9HQU1FEJYBEhMKDkFDS19FTlRFUl9HQU1F",
            "EJcBEhMKDlJFUV9MRUFWRV9HQU1FEJgBEhMKDkFDS19MRUFWRV9HQU1FEJkB",
            "EhMKDlJFUV9TV0FQX1NDRU5FEJsBEhMKDkFDS19TV0FQX1NDRU5FEJwBEhgK",
            "E1JFUV9TV0FQX0hPTUVfU0NFTkUQnQESGAoTQUNLX1NXQVBfSE9NRV9TQ0VO",
            "RRCeARIaChVSRVFfRU5URVJfR0FNRV9GSU5JU0gQnwESGgoVQUNLX0VOVEVS",
            "X0dBTUVfRklOSVNIEKABEhUKEEFDS19PQkpFQ1RfRU5UUlkQyAESFQoQQUNL",
            "X09CSkVDVF9MRUFWRRDJARIeChlBQ0tfT0JKRUNUX1BST1BFUlRZX0VOVFJZ",
            "EMoBEhwKF0FDS19PQkpFQ1RfUkVDT1JEX0VOVFJZEMsBEhUKEEFDS19QUk9Q",
            "RVJUWV9JTlQQ0gESFwoSQUNLX1BST1BFUlRZX0ZMT0FUENMBEhgKE0FDS19Q",
            "Uk9QRVJUWV9TVFJJTkcQ1AESGAoTQUNLX1BST1BFUlRZX09CSkVDVBDWARIZ",
            "ChRBQ0tfUFJPUEVSVFlfVkVDVE9SMhDXARIZChRBQ0tfUFJPUEVSVFlfVkVD",
            "VE9SMxDYARIXChJBQ0tfUFJPUEVSVFlfQ0xFQVIQ2QESEAoLQUNLX0FERF9S",
            "T1cQ3AESEwoOQUNLX1JFTU9WRV9ST1cQ3QESEQoMQUNLX1NXQVBfUk9XEN4B",
            "EhMKDkFDS19SRUNPUkRfSU5UEN8BEhUKEEFDS19SRUNPUkRfRkxPQVQQ4AES",
            "FgoRQUNLX1JFQ09SRF9TVFJJTkcQ4gESFgoRQUNLX1JFQ09SRF9PQkpFQ1QQ",
            "4wESFwoSQUNLX1JFQ09SRF9WRUNUT1IyEOQBEhcKEkFDS19SRUNPUkRfVkVD",
            "VE9SMxDlARIVChBBQ0tfUkVDT1JEX0NMRUFSEPoBEhQKD0FDS19SRUNPUkRf",
            "U09SVBD7ARIWChFBQ0tfREFUQV9GSU5JU0hFRBCEAhINCghSRVFfTU9WRRCs",
            "AhINCghBQ0tfTU9WRRCtAhINCghSRVFfQ0hBVBDeAhINCghBQ0tfQ0hBVBDf",
            "AhIWChFSRVFfU0tJTExfT0JKRUNUWBCQAxIWChFBQ0tfU0tJTExfT0JKRUNU",
            "WBCRAxISCg1SRVFfU0tJTExfUE9TEJIDEhIKDUFDS19TS0lMTF9QT1MQkwMS",
            "FgoRQUNLX09OTElORV9OT1RJRlkQ2AQSFwoSQUNLX09GRkxJTkVfTk9USUZZ",
            "ENkEKkcKCUVJdGVtVHlwZRINCglFSVRfRVFVSVAQABILCgdFSVRfR0VNEAES",
            "DgoKRUlUX1NVUFBMWRACEg4KCkVJVF9TQ1JPTEwQAyq3AQoKRVNraWxsVHlw",
            "ZRIWChJCUklFRl9TSU5HTEVfU0tJTEwQABIVChFCUklFRl9HUk9VUF9TS0lM",
            "TBABEhcKE0JVTExFVF9TSU5HTEVfU0tJTEwQAhIYChRCVUxMRVRfUkVCT1VO",
            "RF9TS0lMTBADEhwKGEJVTExFVF9UQVJHRVRfQk9NQl9TS0lMTBAEEhkKFUJV",
            "TExFVF9QT1NfQk9NQl9TS0lMTBAFEg4KCkZVTkNfU0tJTEwQBipNCgpFU2Nl",
            "bmVUeXBlEhAKDE5PUk1BTF9TQ0VORRAAEhYKElNJTkdMRV9DTE9ORV9TQ0VO",
            "RRABEhUKEU1VTFRJX0NMT05FX1NDRU5FEAIqRgoIRU5QQ1R5cGUSDgoKTk9S",
            "TUFMX05QQxAAEgwKCEhFUk9fTlBDEAESDgoKVFVSUkVUX05QQxACEgwKCEZV",
            "TkNfTlBDEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NFMsg.EGameEventCode), typeof(global::NFMsg.EGameMsgID), typeof(global::NFMsg.EItemType), typeof(global::NFMsg.ESkillType), typeof(global::NFMsg.ESceneType), typeof(global::NFMsg.ENPCType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///events
  /// </summary>
  public enum EGameEventCode {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SUCCESS")] SUCCESS = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKOWN_ERROR")] UNKOWN_ERROR = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_EXIST")] ACCOUNT_EXIST = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNTPWD_INVALID")] ACCOUNTPWD_INVALID = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_USING")] ACCOUNT_USING = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_LOCKED")] ACCOUNT_LOCKED = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_LOGIN_SUCCESS")] ACCOUNT_LOGIN_SUCCESS = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_SUCCESS")] VERIFY_KEY_SUCCESS = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_FAIL")] VERIFY_KEY_FAIL = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_SUCCESS")] SELECTSERVER_SUCCESS = 9,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_FAIL")] SELECTSERVER_FAIL = 10,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_EXIST")] CHARACTER_EXIST = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SVRZONEID_INVALID")] SVRZONEID_INVALID = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NUMOUT")] CHARACTER_NUMOUT = 112,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_INVALID")] CHARACTER_INVALID = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NOTEXIST")] CHARACTER_NOTEXIST = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_USING")] CHARACTER_USING = 115,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_LOCKED")] CHARACTER_LOCKED = 116,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ZONE_OVERLOAD")] ZONE_OVERLOAD = 117,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NOT_ONLINE")] NOT_ONLINE = 118,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("INSUFFICIENT_DIAMOND")] INSUFFICIENT_DIAMOND = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("INSUFFICIENT_GOLD")] INSUFFICIENT_GOLD = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("INSUFFICIENT_SP")] INSUFFICIENT_SP = 202,
  }

  public enum EGameMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKNOW")] UNKNOW = 0,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_RESULT")] EVENT_RESULT = 1,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_TRANSPORT")] EVENT_TRANSPORT = 2,
    /// <summary>
    /// want to close some one
    /// </summary>
    [pbr::OriginalName("CLOSE_SOCKET")] CLOSE_SOCKET = 3,
    [pbr::OriginalName("WTM_WORLD_REGISTERED")] WTM_WORLD_REGISTERED = 10,
    [pbr::OriginalName("WTM_WORLD_UNREGISTERED")] WTM_WORLD_UNREGISTERED = 11,
    [pbr::OriginalName("WTM_WORLD_REFRESH")] WTM_WORLD_REFRESH = 12,
    [pbr::OriginalName("LTM_LOGIN_REGISTERED")] LTM_LOGIN_REGISTERED = 20,
    [pbr::OriginalName("LTM_LOGIN_UNREGISTERED")] LTM_LOGIN_UNREGISTERED = 21,
    [pbr::OriginalName("LTM_LOGIN_REFRESH")] LTM_LOGIN_REFRESH = 22,
    [pbr::OriginalName("PTWG_PROXY_REGISTERED")] PTWG_PROXY_REGISTERED = 30,
    [pbr::OriginalName("PTWG_PROXY_UNREGISTERED")] PTWG_PROXY_UNREGISTERED = 31,
    [pbr::OriginalName("PTWG_PROXY_REFRESH")] PTWG_PROXY_REFRESH = 32,
    [pbr::OriginalName("GTW_GAME_REGISTERED")] GTW_GAME_REGISTERED = 40,
    [pbr::OriginalName("GTW_GAME_UNREGISTERED")] GTW_GAME_UNREGISTERED = 41,
    [pbr::OriginalName("GTW_GAME_REFRESH")] GTW_GAME_REFRESH = 42,
    [pbr::OriginalName("DTW_DB_REGISTERED")] DTW_DB_REGISTERED = 60,
    [pbr::OriginalName("DTW_DB_UNREGISTERED")] DTW_DB_UNREGISTERED = 61,
    [pbr::OriginalName("DTW_DB_REFRESH")] DTW_DB_REFRESH = 62,
    [pbr::OriginalName("STS_NET_INFO")] STS_NET_INFO = 70,
    [pbr::OriginalName("REQ_LAG_TEST")] REQ_LAG_TEST = 80,
    [pbr::OriginalName("ACK_GATE_LAG_TEST")] ACK_GATE_LAG_TEST = 81,
    [pbr::OriginalName("ACK_GAME_LAG_TEST")] ACK_GAME_LAG_TEST = 82,
    [pbr::OriginalName("STS_SERVER_REPORT")] STS_SERVER_REPORT = 90,
    [pbr::OriginalName("STS_HEART_BEAT")] STS_HEART_BEAT = 100,
    /// <summary>
    ///////////////////////////////////////////////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("REQ_LOGIN")] REQ_LOGIN = 101,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOGIN")] ACK_LOGIN = 102,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LOGOUT")] REQ_LOGOUT = 103,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_WORLD_LIST")] REQ_WORLD_LIST = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_WORLD_LIST")] ACK_WORLD_LIST = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_WORLD")] REQ_CONNECT_WORLD = 112,
    [pbr::OriginalName("ACK_CONNECT_WORLD")] ACK_CONNECT_WORLD = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_KICKED_FROM_WORLD")] REQ_KICKED_FROM_WORLD = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_KEY")] REQ_CONNECT_KEY = 120,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_CONNECT_KEY")] ACK_CONNECT_KEY = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SELECT_SERVER")] REQ_SELECT_SERVER = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SELECT_SERVER")] ACK_SELECT_SERVER = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ROLE_LIST")] REQ_ROLE_LIST = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ROLE_LIST")] ACK_ROLE_LIST = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CREATE_ROLE")] REQ_CREATE_ROLE = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_DELETE_ROLE")] REQ_DELETE_ROLE = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_RECOVER_ROLE")] REQ_RECOVER_ROLE = 136,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LOAD_ROLE_DATA")] REQ_LOAD_ROLE_DATA = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOAD_ROLE_DATA")] ACK_LOAD_ROLE_DATA = 141,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SAVE_ROLE_DATA")] REQ_SAVE_ROLE_DATA = 142,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SAVE_ROLE_DATA")] ACK_SAVE_ROLE_DATA = 143,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME")] REQ_ENTER_GAME = 150,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME")] ACK_ENTER_GAME = 151,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LEAVE_GAME")] REQ_LEAVE_GAME = 152,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LEAVE_GAME")] ACK_LEAVE_GAME = 153,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_SCENE")] REQ_SWAP_SCENE = 155,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_SCENE")] ACK_SWAP_SCENE = 156,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_HOME_SCENE")] REQ_SWAP_HOME_SCENE = 157,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_HOME_SCENE")] ACK_SWAP_HOME_SCENE = 158,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME_FINISH")] REQ_ENTER_GAME_FINISH = 159,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME_FINISH")] ACK_ENTER_GAME_FINISH = 160,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_ENTRY")] ACK_OBJECT_ENTRY = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_LEAVE")] ACK_OBJECT_LEAVE = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_PROPERTY_ENTRY")] ACK_OBJECT_PROPERTY_ENTRY = 202,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_RECORD_ENTRY")] ACK_OBJECT_RECORD_ENTRY = 203,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_INT")] ACK_PROPERTY_INT = 210,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_FLOAT")] ACK_PROPERTY_FLOAT = 211,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_STRING")] ACK_PROPERTY_STRING = 212,
    /// <summary>
    ///EGMI_ACK_PROPERTY_DOUBLE				= 213;			//
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_OBJECT")] ACK_PROPERTY_OBJECT = 214,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR2")] ACK_PROPERTY_VECTOR2 = 215,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR3")] ACK_PROPERTY_VECTOR3 = 216,
    [pbr::OriginalName("ACK_PROPERTY_CLEAR")] ACK_PROPERTY_CLEAR = 217,
    [pbr::OriginalName("ACK_ADD_ROW")] ACK_ADD_ROW = 220,
    [pbr::OriginalName("ACK_REMOVE_ROW")] ACK_REMOVE_ROW = 221,
    [pbr::OriginalName("ACK_SWAP_ROW")] ACK_SWAP_ROW = 222,
    [pbr::OriginalName("ACK_RECORD_INT")] ACK_RECORD_INT = 223,
    [pbr::OriginalName("ACK_RECORD_FLOAT")] ACK_RECORD_FLOAT = 224,
    /// <summary>
    ///EGMI_ACK_RECORD_DOUBLE				= 225;
    /// </summary>
    [pbr::OriginalName("ACK_RECORD_STRING")] ACK_RECORD_STRING = 226,
    [pbr::OriginalName("ACK_RECORD_OBJECT")] ACK_RECORD_OBJECT = 227,
    [pbr::OriginalName("ACK_RECORD_VECTOR2")] ACK_RECORD_VECTOR2 = 228,
    [pbr::OriginalName("ACK_RECORD_VECTOR3")] ACK_RECORD_VECTOR3 = 229,
    [pbr::OriginalName("ACK_RECORD_CLEAR")] ACK_RECORD_CLEAR = 250,
    [pbr::OriginalName("ACK_RECORD_SORT")] ACK_RECORD_SORT = 251,
    [pbr::OriginalName("ACK_DATA_FINISHED")] ACK_DATA_FINISHED = 260,
    [pbr::OriginalName("REQ_MOVE")] REQ_MOVE = 300,
    [pbr::OriginalName("ACK_MOVE")] ACK_MOVE = 301,
    [pbr::OriginalName("REQ_CHAT")] REQ_CHAT = 350,
    [pbr::OriginalName("ACK_CHAT")] ACK_CHAT = 351,
    [pbr::OriginalName("REQ_SKILL_OBJECTX")] REQ_SKILL_OBJECTX = 400,
    [pbr::OriginalName("ACK_SKILL_OBJECTX")] ACK_SKILL_OBJECTX = 401,
    [pbr::OriginalName("REQ_SKILL_POS")] REQ_SKILL_POS = 402,
    [pbr::OriginalName("ACK_SKILL_POS")] ACK_SKILL_POS = 403,
    [pbr::OriginalName("ACK_ONLINE_NOTIFY")] ACK_ONLINE_NOTIFY = 600,
    [pbr::OriginalName("ACK_OFFLINE_NOTIFY")] ACK_OFFLINE_NOTIFY = 601,
  }

  public enum EItemType {
    /// <summary>
    ///the equipment which can add props
    /// </summary>
    [pbr::OriginalName("EIT_EQUIP")] EIT_EQUIP = 0,
    /// <summary>
    ///the gem ca be embed to the equipment
    /// </summary>
    [pbr::OriginalName("EIT_GEM")] EIT_GEM = 1,
    /// <summary>
    ///expendable items for player, such as a medicine that cures
    /// </summary>
    [pbr::OriginalName("EIT_SUPPLY")] EIT_SUPPLY = 2,
    /// <summary>
    ///special items that can call a hero or others, special items can do what you want to do
    /// </summary>
    [pbr::OriginalName("EIT_SCROLL")] EIT_SCROLL = 3,
  }

  public enum ESkillType {
    /// <summary>
    ///this kind of skill just can damage one object
    /// </summary>
    [pbr::OriginalName("BRIEF_SINGLE_SKILL")] BRIEF_SINGLE_SKILL = 0,
    /// <summary>
    ///this kind of skill can damage multiple objects
    /// </summary>
    [pbr::OriginalName("BRIEF_GROUP_SKILL")] BRIEF_GROUP_SKILL = 1,
    /// <summary>
    ///this kind of bullet just can damage one object
    /// </summary>
    [pbr::OriginalName("BULLET_SINGLE_SKILL")] BULLET_SINGLE_SKILL = 2,
    /// <summary>
    ///this kind of bullet can damage multiple objects via rebound
    /// </summary>
    [pbr::OriginalName("BULLET_REBOUND_SKILL")] BULLET_REBOUND_SKILL = 3,
    /// <summary>
    ///this kind of bullet can damage multiple objects who around the target when the bullet touched the target object
    /// </summary>
    [pbr::OriginalName("BULLET_TARGET_BOMB_SKILL")] BULLET_TARGET_BOMB_SKILL = 4,
    /// <summary>
    ///this kind of bullet can damage multiple objects  who around the target when the bullet arrived the position
    /// </summary>
    [pbr::OriginalName("BULLET_POS_BOMB_SKILL")] BULLET_POS_BOMB_SKILL = 5,
    [pbr::OriginalName("FUNC_SKILL")] FUNC_SKILL = 6,
  }

  public enum ESceneType {
    /// <summary>
    ///public town, only has one group available for players is 1
    /// </summary>
    [pbr::OriginalName("NORMAL_SCENE")] NORMAL_SCENE = 0,
    /// <summary>
    ///private room, only has one player per group and it will be destroyed if the player leaved from group.
    /// </summary>
    [pbr::OriginalName("SINGLE_CLONE_SCENE")] SINGLE_CLONE_SCENE = 1,
    /// <summary>
    ///private room, only has more than one player per group and it will be destroyed if all players leaved from group.
    /// </summary>
    [pbr::OriginalName("MULTI_CLONE_SCENE")] MULTI_CLONE_SCENE = 2,
  }

  public enum ENPCType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NORMAL_NPC")] NORMAL_NPC = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("HERO_NPC")] HERO_NPC = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TURRET_NPC")] TURRET_NPC = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("FUNC_NPC")] FUNC_NPC = 3,
  }

  #endregion

}

#endregion Designer generated code
