--
-- $Id$
--

module( "resmng" )
prop_effect_typeKey = {
ID = 1, Index = 2, Default = 3, Parent = 4, Hash = 5, Func = 6, ObjType = 7, IsBattle = 8, Positive = 9, ShowPage = 10, ShowPer = 11, Icon = 12, ShowType = 13, BuffName = 14, EffectIcon = 15, DisplayType = 16, BuffNameARG = 17, BuffDesc = 18, SoldierIcon = 19, TroopIcon = 20, Category = 21, ATKPower = 22, RPGType = 23, ColorLevel = 24, 
}

prop_effect_type_TypeInfo = { Parent = [[Maybe(Ref('prop_effect_type'))]],  Func = [[Int]],  BuffName = [[LangId]],  BuffDesc = [[Maybe(LangId)]], }

prop_effect_type = {

	["RPG_Atk"] = { ID = "RPG_Atk", Index = 10000, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400300, EffectIcon = "icon_attribute_101", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400694, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 14, RPGType = 1000, ColorLevel = {14,28,42,56,70},},
	["RPG_Def"] = { ID = "RPG_Def", Index = 10001, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400301, EffectIcon = "icon_attribute_102", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400695, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 35, RPGType = 1000, ColorLevel = {2.4,4.8,7.2,9.6,12},},
	["RPG_Hp"] = { ID = "RPG_Hp", Index = 10002, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_103", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 0.5, RPGType = 1000, ColorLevel = {190,380,570,760,950},},
	["RPG_Crit"] = { ID = "RPG_Crit", Index = 10101, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400317, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400711, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 35, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_CritAnti"] = { ID = "RPG_CritAnti", Index = 10102, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400318, EffectIcon = "icon_attribute_204", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400712, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 35, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_Accuracy"] = { ID = "RPG_Accuracy", Index = 10103, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400319, EffectIcon = "icon_attribute_205", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400713, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 35, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_Dodge"] = { ID = "RPG_Dodge", Index = 10104, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400320, EffectIcon = "icon_attribute_206", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400714, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 70, RPGType = 1, ColorLevel = {10,20,30,40,50},},
	["RPG_BlockAnti"] = { ID = "RPG_BlockAnti", Index = 10105, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400321, EffectIcon = "icon_attribute_208", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400715, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 35, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_Block"] = { ID = "RPG_Block", Index = 10106, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400322, EffectIcon = "icon_attribute_207", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400716, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 35, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_Lifesteal"] = { ID = "RPG_Lifesteal", Index = 10201, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400323, EffectIcon = "icon_attribute_209", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400717, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_CritEnhance"] = { ID = "RPG_CritEnhance", Index = 10202, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400324, EffectIcon = "icon_attribute_202", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400718, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 43.75, RPGType = 1, ColorLevel = {16,32,48,64,80},},
	["RPG_CritReduce"] = { ID = "RPG_CritReduce", Index = 10203, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400325, EffectIcon = "icon_attribute_203", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400719, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 35, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_MagicReduce"] = { ID = "RPG_MagicReduce", Index = 10204, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400326, EffectIcon = "icon_attribute_210", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400720, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 38.5, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_DamageReduce"] = { ID = "RPG_DamageReduce", Index = 10205, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400327, EffectIcon = "icon_attribute_211", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400721, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 38.5, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_MagicIncrease"] = { ID = "RPG_MagicIncrease", Index = 10206, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400328, EffectIcon = "icon_attribute_210", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400722, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 38.5, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_DamageIncrease"] = { ID = "RPG_DamageIncrease", Index = 10207, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400329, EffectIcon = "icon_attribute_211", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400723, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 38.5, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_FinalReduce"] = { ID = "RPG_FinalReduce", Index = 10208, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400330, EffectIcon = "icon_attribute_210", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400724, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 38.5, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_FinalIncrease"] = { ID = "RPG_FinalIncrease", Index = 10209, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400331, EffectIcon = "icon_attribute_211", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400725, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 38.5, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_HpSp"] = { ID = "RPG_HpSp", Index = 10301, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400332, EffectIcon = "icon_attribute_212", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400726, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 490, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_Heal"] = { ID = "RPG_Heal", Index = 10302, Default = 10000, Parent = nil, Hash = nil, Func = 11, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400333, EffectIcon = "icon_attribute_213", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400727, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 4.4, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_Health"] = { ID = "RPG_Health", Index = 10303, Default = 10000, Parent = nil, Hash = nil, Func = 11, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400334, EffectIcon = "icon_attribute_214", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400728, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 4.4, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_AtkSp"] = { ID = "RPG_AtkSp", Index = 10304, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400335, EffectIcon = "icon_attribute_215", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400729, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 87.5, RPGType = 1, ColorLevel = {20,40,60,80,100},},
	["RPG_SkillSp"] = { ID = "RPG_SkillSp", Index = 10305, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400336, EffectIcon = "icon_attribute_216", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400730, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 160, RPGType = 0.667, ColorLevel = {3,6,9,12,15},},
	["RPG_Sp"] = { ID = "RPG_Sp", Index = 10306, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400303, EffectIcon = "icon_attribute_216", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400697, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 0.004, ColorLevel = {20,40,60,80,100},},
	["RPG_Dist"] = { ID = "RPG_Dist", Index = 10307, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400304, EffectIcon = "icon_attribute_101", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400698, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1, ColorLevel = {999,999,999,999,999},},
	["RPG_Anger"] = { ID = "RPG_Anger", Index = 10308, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_AngerSp"] = { ID = "RPG_AngerSp", Index = 10310, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_AngerHit"] = { ID = "RPG_AngerHit", Index = 10311, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_AngerKill"] = { ID = "RPG_AngerKill", Index = 10312, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_HpMax"] = { ID = "RPG_HpMax", Index = 10401, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_103", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_AngerMax"] = { ID = "RPG_AngerMax", Index = 10402, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_StarFactor"] = { ID = "RPG_StarFactor", Index = 10403, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_StarValue"] = { ID = "RPG_StarValue", Index = 10404, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = nil, RPGType = 1000, ColorLevel = {999,999,999,999,999},},
	["RPG_StarEffect"] = { ID = "RPG_StarEffect", Index = 10405, Default = nil, Parent = nil, Hash = nil, Func = 1, ObjType = nil, IsBattle = nil, Positive = 1, ShowPage = nil, ShowPer = nil, Icon = nil, ShowType = 1, BuffName = LG_BUFF_NAME_102400302, EffectIcon = "icon_attribute_201", DisplayType = 1, BuffNameARG = nil, BuffDesc = LG_BUFF_DES_102400696, SoldierIcon = nil, TroopIcon = nil, Category = nil, ATKPower = 54.5, RPGType = 1, ColorLevel = {999,999,999,999,999},},
}


function prop_effect_type_byid(_key_id)
    local id_data = prop_effect_type[_key_id]
    if id_data == nil then
        ERROR("[resmng] get_conf: invalid key %s for prop_effect_type", _key_id)
        return
    end
    return id_data
end

