---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.wei
--- DateTime: 2023/1/4 10:19
--- rpg表现层常量定义

RPG_BATTLE_TEXT_TYPE = {
    HP_NORMAL = 1, -- 普通伤害
    HP_CRIT = 2, -- 暴击伤害    
    HP_RECOVER = 3, -- 血量回复
    HP_BLOCK = 4, -- 怒气增加

    ANGER_ADD = 5, -- 怒气增加

    ATT_STYLE_BLUE = 6, -- 属性改变降低 蓝色
    ATT_STYLE_RED = 7, -- 属性改变降低 红色
    TEXT_STATE_1 = 8, -- 状态文本 1 红色
    TEXT_STATE_2 = 9, -- 状态文本 2 蓝色
}